# Site settings
title: 'infogbb' # Your Title
tagline: 'Contenitore comunicati Curva Sud Ambrì' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: kramdown

url: http://cyberl3o.github.io

# Gems
plugins:
  - jekyll-paginate

